Add kopano konnect and a caddy as proxy
owncloud-docker/compose-playground pull request #4
Opened 2020-02-11 14:37 UTC by DeepDiver1975

2020-02-12 14:13 UTC, michaelstingl commented
> Setup the domain name in etch/hosts - assuming you are on linux

Local setup is not in my scope and no requirement for client dev and qa. Sorry.

2020-02-12 14:30 UTC, DeepDiver1975 commented
> Local setup is not in my scope and no requirement for client dev and qa. Sorry.

maybe not explicit enough - or setup dns in what ever way you want it to work.
etc/hosts is the simplest way to test this.

2020-02-12 14:59 UTC, michaelstingl commented
> maybe not explicit enough - or setup dns in what ever way you want it to work.
> etc/hosts is the simplest way to test this.

Okay, I'll try it…

2020-02-16 23:12 UTC, xoxys requested changes
Just a few formatting :)

2020-02-16 23:12 UTC, xoxys commented on kopano/konnect/README.md
> +Setup the domain name in etch/hosts - assuming you are on linux
Typo, should be `/etc/hosts`

2020-02-16 23:12 UTC, xoxys commented on kopano/konnect/README.md
> +```
Please add language selector "```console"

2020-02-16 23:12 UTC, xoxys commented on kopano/konnect/konnectd-identifier-registration.yaml
> +
Remove empty line and fix indentation (remove 4 spaces at the beginning of each line)

2020-02-17 10:37 UTC, xoxys approved these changes
LGTM

2020-02-17 19:12 UTC, merged