Add defaults to swith the base url
owncloud-docker/compose-playground pull request #9
Opened 2020-03-30 09:01 UTC by micbar

2020-03-30 09:21 UTC, micbar commented
@michaelstingl

2020-03-30 21:00 UTC, xoxys requested changes

2020-03-30 21:00 UTC, xoxys commented on ocis/config/identifier-registration.yml
> +          - https://cloud.local:9200
IMO cloud.local and your IP addresses should be dropped

2020-03-30 21:00 UTC, xoxys commented on ocis/config/identifier-registration.yml
> +          - https://cloud.local:9200
same here

2020-03-31 08:43 UTC, micbar commented on ocis/config/identifier-registration.yml
> +          - https://cloud.local:9200
i would like to set an example base url to make it more understandable.

Should we use a more generic IP like 10.255.255.255 ?

2020-03-31 08:43 UTC, micbar commented on ocis/config/identifier-registration.yml
> +          - https://cloud.local:9200
same

2020-03-31 12:59 UTC, xoxys commented on ocis/config/identifier-registration.yml
> +          - https://cloud.local:9200
Then you could leave this IP if you would like to. But this should be a) a comment or b) part of some documentation. But at the end if it does not hurt you could also leave it like this. It's just a bit "ugly"

2020-03-31 13:12 UTC, xoxys approved these changes

2020-03-31 13:14 UTC, merged

2020-04-03 13:25 UTC, michaelstingl commented
After the merge of https://github.com/owncloud-docker/compose-playground/issues/11 , it works very nice with 2.7 desktop client and 1.3.2 iOS app 👍 

```
git clone https://github.com/owncloud-docker/compose-playground.git

cd compose-playground/ocis

sed -i -e 's/your-url/192.168.103.195/g' config/identifier-registration.yml

cat << EOF > .env
OCIS_BASE_URL=192.168.103.195
OCIS_HTTP_PORT=9200
OCIS_DOCKER_TAG=latest
EOF

docker-compose -f ocis.yml -f ../cache/redis-ocis.yml up -d

curl -k https://192.168.103.195:9200/status.php
```